Solve the questions below using Numpy only.

#  **1. Numpy Arrays**

### Bài 1: Khởi tạo vector
Khởi tạo một vector gồm `n` phần tử gồm toàn số 0.

Input:
```
n = 5
```

Output:
```
[0, 0, 0, 0, 0]
```

In [9]:
import numpy as np

n = int(input())
vector = np.zeros(n, dtype= np.int8)
print(vector.tolist())

[0, 0, 0, 0, 0]


### Bài 2: Khởi tạo vector
Khởi tạo một vector gồm `n` phần tử gồm toàn số 1.

Input:
```
n = 5
```

Output:
```
[1, 1, 1, 1, 1]
```

In [10]:
n = int(input())
vector = np.ones(n, dtype= np.int8)
print(vector.tolist())

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


### Bài 3: Khởi tạo vector
Khởi tạo một vector gồm `n` phần tử gồm toàn số `x`.

Input:
```
n = 5
x = 3.5
```

Output:
```
[3.5, 3.5, 3.5, 3.5, 3.5]
```

In [12]:
n = int(input())
x = float(input())
vector = np.full(n,x, dtype= np.float16)
vector

array([3.5, 3.5, 3.5, 3.5, 3.5], dtype=float16)

### Bài 4: Khởi tạo vector
Khởi tạo một vector có số phần tử là `n` gồm các số nguyên tăng dần từ `0..n-1`.

Input:
```
n = 5
```

Output:
```
[0, 1, 2, 3, 4]
```

In [ ]:
n = int(input())
vector = np.arange(n)
vector

array([0, 1, 2, 3, 4])

### Bài 5: Khởi tạo vector
Khởi tạo một vector có số phần tử là `n` gồm các số nguyên tăng dần từ `x, x+1,...,x+n-1` (chuỗi số bắt đầu từ `x`)

Ví dụ:

Input:
```
n = 5
x = 3.5
```

Output:
```
[3.5, 4.5, 5.5, 6.5, 7.5]
```

In [17]:
n = int(input())
x = float(input())
vector = np.arange(x, n + x)
vector

array([3.5, 4.5, 5.5, 6.5, 7.5])

### Bài 6: Khởi tạo ma trận
Khởi tạo ma trận kích thước `m x n` gồm toàn số `K`.

Ví dụ:

Input:
```
m = 3
n = 4
K = 5
```

Output:
```
[[5, 5, 5, 5], [5, 5, 5, 5], [5, 5, 5, 5]]
```

In [18]:
m = int(input())
n = int(input())
k = float(input())
matrix = np.full(shape=(m,n),fill_value=k)
matrix

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

### Bài 7: Khởi tạo ma trận
Khởi tạo ma trận kích thước `m x n` gồm tăng dần từ trái sang phải, từ trên xuống dưới. Phần tử nhỏ nhất bắt đầu từ 1.

Ví dụ:

Input:
```
m = 2
n = 4
```

Output:
```
[[1, 2, 3, 4], [5, 6, 7, 8]]
```

In [19]:
m = int(input())
n = int(input())
matrix = np.arange(1,m * n + 1).reshape(m,n)
matrix

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Bài 8: Tích vô hướng 2 vector
Viết hàm `solution` nhận vào 2 List `a` và `b` có kiểu dữ liệu là `float`, tính tích vô hướng giữa hai vector `a` và `b`.

Ví dụ:

Input:
```
a = [1, 2]
b = [3, 4]
```

Output:
```
11
```

In [25]:
def solution(a, b):
    a = np.array(a)
    b = np.array(b)
    return a @ b
# np.dot(a,b)

a = [1, 2]
b = [3, 4]
solution(a,b)

np.int64(11)

### Bài 9: Tích vô hướng 2 ma trận
Viết hàm nhận vào hai *ma trận* `X` và *ma trận* `W`, trả về giá trị tích `M` (dot product) theo công thức sau:
```
M = (x^T)W
```
Trong đó, `x^T` là phép chuyển vị của `x`. Cần kiểm tra số chiều để bảo đảm phép tính luôn tính được trước khi thực hiện phép tính, trả về giá trị `None` nếu số chiều không tương thích.

Ví dụ:


Input:
```
X = [[1, 1, 1],
    [0, 0, 0]]

W = [[1, 1, 1],
    [0, 0, 0]]
```

Output:
```
[[1, 1, 1],
 [1, 1, 1],
 [1, 1, 1]]
```

In [29]:
def solution(X, W):
    X = np.array(X)
    W = np.array(W)

    if X.shape[0] != W.shape[0]:
        return None

    return X.T @ W

X = [[1, 1, 1],
    [0, 0, 0]]

W = [[1, 1, 1],
    [0, 0, 0]]
solution(X,W)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### Bài 10: Tổng các ma trận và vector
Viết hàm nhận vào hai ma trận `X` và `W`, trả về giá trị `M` theo công thức sau:
```
M = 2 (X^T + W).X
```
Trong đó `X^T` là phép chuyển vị của `X`. Cần kiểm tra số chiều để bảo đảm phép tính luôn tính được trước khi thực hiện phép tính, trả về giá trị `None` nếu số chiều không tương thích.

Input:
```
X = [[1, 1],
    [0, 0]
]

W = [[1, 1],
    [0, 0]
]
```

Output:
```
[[4, 4],
[2, 2]]
```

In [ ]:
import numpy as np

def solution(X, W):
    X = np.array(X)
    W = np.array(W)

    if X.T.shape != W.shape:
        return None

    return 2 * (X.T + W) @ X

array([[1, 1],
       [1, 1]])

# **2. Numpy Arrays Practice**

### Bài 1: Gửi tiết kiệm
Tính số tiền còn lại trong tài khoản ngân hàng với đầu vào là
danh sách các số tiền giao dịch, tương ứng là sẽ có danh sách
các loại giao dịch gửi tiền (ký hiệu bằng chuỗi 'D'), rút tiền 
(ký hiệu bằng chuỗi 'W')

**Input:**
   - moneys: kiểu List, chứa danh sách các số tiền giao dịch
   (gửi và rút khỏi tài khoản)
   - types: kiểu List, chứa danh sách các loại giao dịch 
   (gửi ký hiệu là 'D', rút ký hiệu là 'W')

**Output:**
   - Kiểu số thực, số tiền còn lại trong tài khoản

Ví dụ:

Input:
```
moneys = [400.0, 100.0, 200.0]
types = ['D', 'W', 'D']
```

Output:
```
500.0
```

In [1]:
import numpy as np

def solution(moneys, types):
    moneys = np.array(moneys)

    types = np.array(types)

    balance = np.sum(np.where(types == 'D', moneys, -moneys))

    return float(balance)
moneys = [400.0, 100.0, 200.0]
types = ['D', 'W', 'D']

print(solution(moneys, types))

500.0


### Bài 2: Điểm trung bình
Tính điểm trung bình của một bạn sinh viên biết trước danh sách các điểm số và số tín chỉ của từng môn học.

**Input:**
   - marks: kiểu List, gồm *n* phần tử. Đây là điểm các môn của một sinh viên.
   - credits: kiểu List, gồm *n* phần tử. Đây là số tín chỉ lần lượt của các môn.   
   
**Output:**
   - Kiểu số thực, điểm trung bình của các môn học của sinh viên

Ví dụ:

Input:
```
marks = [8.0, 9.0, 10.0]
credits = [2, 2, 1]
```

Output:
```
8.8
```

In [ ]:
import numpy as np

def solution(marks, credits):
    marks = np.array(marks)
    credits = np.array(credits)

    return float(np.sum(marks * credits) / np.sum(credits))

### Bài 3:
Đếm số lượng sinh viên có điểm số không dưới K điểm cho trước của một lớp học.

**Input:**

    - marks: kiểu List. Đây là điểm toán cả n sinh viên trong lớp.
    - K: kiểu số thực, điểm chuẩn.
   
**Output:**

    - Kiểu số nguyên, số lượng sinh viên trong lớp đạt từ K điểm trở lên

In [ ]:
import numpy as np

def solution(marks, K):
    marks = np.array(marks)

    return int(np.sum(marks >= K))

### Bài 4:
Tính điểm trung bình cao nhất của một lớp học biết trước danh sách các điểm số và số tín chỉ
cho từng môn học của một lớp.

**Input:**
   - marks: kiểu numpy array, kích thước m x n. Đây là điểm các môn của một lớp học. Trong đó, m là số sinh viên, n là số môn học
   - credits: kiểu numpy array, kích thước 1 x n. Đây là số tín chỉ lần lượt của các môn. 
   
**Output:**
   - Kiểu số thực, điểm trung bình của sinh viên cao nhất.

Ví dụ:

Input:
```
marks = np.array(
   [[8.0, 9.0, 10.0],
   [7.0, 9.0, 8.0],
   [8.0, 8.0, 8.0],
   [10.0, 9.0, 7.0],
   [9.0, 9.0, 10.0]
])

credits = np.array([2,2,1])
```

Output:
```
9.2
```

In [ ]:
import numpy as np

def solution(marks, credits):
    weighted_marks = marks * credits

    averages = np.sum(weighted_marks, axis=1) / np.sum(credits)

    return float(np.max(averages))

### Bài 5:
Tính điểm trung bình tích luỹ của từng sinh viên trong lớp học biết trước 
danh sách các điểm số và số tín chỉ cho từng môn học của một lớp. 

**Lưu ý:** khi tính điểm trung bình ta sẽ loại bỏ các điểm và các tín chỉ của môn dưới 5 điểm (rớt).

**Công thức tính điểm trung bình tích lũy:**
   - ĐTBTL = (điểm môn 1 * số tín chỉ môn 1 + ... + điểm môn n * số tín chỉ môn n) / tổng số tín chỉ

**Input:**
   - marks: kiểu numpy array, kích thước m x n. Đây là điểm các môn của một lớp học.
   Trong đó, m là số sinh viên, n là số môn học
   - credits: kiểu numpy array, kích thước 1 x n. Đây là số tín chỉ lần lượt của các môn. 

**Output:**
   - Kiểu numpy array, kích thước 1 x m, chứa điểm trung bình của các bạn sinh viên trong lớp.

Ví dụ:

Input:
```
marks = np.array([
    [8.0, 9.0, 10.0],
    [4.0, 9.0, 8.0],
    [8.0, 3.0, 8.0],
    [10.0, 9.0, 5.0],
    [9.0, 9.0, 4.0]
])

credits = np.array([2, 2, 1])
```

Output:
```
array([8.8, 8.66666667, 8., 8.6, 9.])
```

In [ ]:
import numpy as np

def solution(marks, credits):
    passed = marks >= 5
    weighted_marks = np.where(passed, marks * credits, 0)
    valid_credits = np.where(passed, credits, 0)
    averages = np.sum(weighted_marks, axis=1) / np.sum(valid_credits, axis=1)
    return averages